import { Html, Head, Main, NextScript } from 'next/document'
import Document from 'next/document'
import { ServerStyleSheet } from 'styled-components'


class EditedDocument extends Document {
  render() {
    return (
      <Html lang="en">
        <Head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link href="https://fonts.googleapis.com/css2?family=Goldman:wght@400;700&family=Julius+Sans+One&family=Orbitron:wght@400;500;600;700;800;900&family=Share+Tech&display=swap" rel="stylesheet" />
          <title>Project Leviathan: Warhammer Armor Repository</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <body>
          <main>
            <NextScript />
          </main>
        </body>
      </Html>
    );
  }
}

export default class MyDocument extends EditedDocument {
  static async getInitialProps(ctx) {
    const sheet = new ServerStyleSheet()
    const originalRenderPage = ctx.renderPage

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: App => props => sheet.collectStyles(<App {...props} />)
        })

      const initialProps = await Document.getInitialProps(ctx)
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        )
      }
    } finally {
      sheet.seal()
    }
  }
}